"""quitar columnda estado2

Revision ID: 838c8a471601
Revises: 19874b3f4327
Create Date: 2025-10-08 10:10:17.945821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '838c8a471601'
down_revision: Union[str, Sequence[str], None] = '19874b3f4327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'estado2')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('estado2', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
